// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB50nMUL0YO2u-sS-pTpm4gNyTSl8qnDfE',
    appId: '1:215076918515:web:713164d6e8aa1e23a1d386',
    messagingSenderId: '215076918515',
    projectId: 'byteproject-355e5',
    authDomain: 'byteproject-355e5.firebaseapp.com',
    storageBucket: 'byteproject-355e5.appspot.com',
    measurementId: 'G-S0KW48DQHC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ2FIZ1YgwiwXeNcn53pCHtrbv1DmFCh8',
    appId: '1:541941146484:android:14db37862d5cfe5c9c4221',
    messagingSenderId: '541941146484',
    projectId: 'bytetcms',
    storageBucket: 'bytetcms.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA0tHSUYiyrpqpqUf5Di2pmL8f6o_YKJE',
    appId: '1:215076918515:ios:707ee45cc57ac688a1d386',
    messagingSenderId: '215076918515',
    projectId: 'byteproject-355e5',
    storageBucket: 'byteproject-355e5.appspot.com',
    iosBundleId: 'com.example.dreamLearnApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDA0tHSUYiyrpqpqUf5Di2pmL8f6o_YKJE',
    appId: '1:215076918515:ios:707ee45cc57ac688a1d386',
    messagingSenderId: '215076918515',
    projectId: 'byteproject-355e5',
    storageBucket: 'byteproject-355e5.appspot.com',
    iosBundleId: 'com.example.dreamLearnApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB50nMUL0YO2u-sS-pTpm4gNyTSl8qnDfE',
    appId: '1:215076918515:web:6047dca24617395ca1d386',
    messagingSenderId: '215076918515',
    projectId: 'byteproject-355e5',
    authDomain: 'byteproject-355e5.firebaseapp.com',
    storageBucket: 'byteproject-355e5.appspot.com',
    measurementId: 'G-GQL4FJCJ73',
  );
}